export type LanguagePreference = "system" | "zh" | "en";
export type ResolvedLanguage = "zh" | "en";
export type ThemePreference = "system" | "light" | "dark";
export type ResolvedTheme = "light" | "dark";

export function resolveLanguage(preference: LanguagePreference): ResolvedLanguage {
  if (preference === "zh" || preference === "en") {
    return preference;
  }
  if (typeof navigator !== "undefined" && navigator.language.toLowerCase().startsWith("zh")) {
    return "zh";
  }
  return "en";
}

export function resolveTheme(preference: ThemePreference): ResolvedTheme {
  if (preference === "light" || preference === "dark") {
    return preference;
  }
  if (typeof window !== "undefined" && window.matchMedia("(prefers-color-scheme: dark)").matches) {
    return "dark";
  }
  return "light";
}

export const COPY = {
  zh: {
    appTitle: "iDeer",
    desktopTitle: "iDeer Desktop",
    brandSubtitle: "每日智能简报",
    previewBadge: "预览",
    statusConnected: "服务已连接",
    statusWaitingDesktop: "等待启动本地服务",
    statusWaitingWeb: "请先启动 Python 后端",
    statusBackendStarted: "本地服务已启动",
    statusBackendStopped: "已停止托管服务",
    statusConfigSaved: "配置已保存",
    statusRunDone: (date: string) => `完成于 ${date}`,
    statusRunExited: "任务退出",
    statusSocketError: "WebSocket 连接异常",
    sidebar: {
      home: "概览",
      library: "资料库",
    },
    home: {
      title: "欢迎回来",
      description: "在这里运行今日简报、查看历史结果，以及管理你的常用配置。",
      openSettings: "打开用户中心",
      runBlockedBackend: "请先启动本地服务，运行按钮才会可用。",
      runBlockedSources: "请至少选择一个信息源。",
      runBlockedRunning: "当前任务仍在运行中，请等待完成。",
      backend: "后端服务",
      online: "在线",
      offline: "离线",
      startBackend: "启动本地服务",
      startingBackend: "启动中...",
      refresh: "刷新数据",
      refreshing: "刷新中...",
      stopBackend: "停止托管服务",
      model: "模型配置",
      mail: "邮件投递",
      mailReady: "已配置",
      mailPending: "待配置",
      noReceiver: "尚未设置默认接收邮箱",
      sources: "信息源",
      noSourcesActive: "尚未开启信息源。",
      recentRuns: "最近结果",
      noHistory: "还没有历史记录，先运行一轮看看。",
    },
    workbench: {
      title: "运行面板",
      run: "开始运行",
      running: "运行中...",
      receiver: "接收邮箱",
      deliveryMode: "投递模式",
      sourceEmails: "按来源分别发送",
      combinedReport: "合并汇总发送",
      both: "两者都发",
      report: "生成跨源报告",
      ideas: "生成研究想法",
      save: "保存历史结果",
      description: "兴趣描述",
      positiveTags: "正向偏好",
      negativeTags: "负向过滤",
      positivePlaceholder: "输入想关注的主题，回车添加",
      negativePlaceholder: "输入想屏蔽的主题，回车添加",
      addTag: "添加",
      saveInterest: "保存为默认兴趣",
      savingInterest: "保存中...",
      scholarUrl: "Scholar URL",
      extraX: "本次追加 X 账号",
      researcherProfile: "研究者画像",
      advanced: "高级设置",
      logs: "实时日志",
      outputs: "输出文件",
      outputEmpty: "完成后会在这里列出本次生成的文件。",
      logEmpty: "运行后这里会显示实时输出。",
      refreshHistory: "刷新历史",
    },
    library: {
      title: "历史运行记录",
      refresh: "刷新",
      refreshing: "刷新中...",
      empty: "暂无历史记录。",
      details: "结果详情",
      emptyDetails: "选择左侧记录查看 Markdown、HTML 和 JSON 输出。",
      noMarkdown: "无 Markdown 文件",
      noHtml: "无 HTML 文件",
      noJson: "无 JSON 文件",
    },
    settings: {
      controlCenter: "控制中心",
      userCenter: "用户中心",
      basic: "基础设置",
      save: "保存设置",
      saving: "保存中...",
      preferences: "偏好",
      language: "语言",
      theme: "显示模式",
      followSystem: "跟随系统",
      chinese: "中文",
      english: "English",
      dark: "深色",
      light: "浅色",
      model: "模型与投递配置",
      content: "内容偏好",
      advanced: "高级设置",
      provider: "Provider",
      modelName: "Model",
      temperature: "Temperature",
      baseUrl: "Base URL",
      apiKey: "API Key",
      smtpServer: "SMTP Server",
      smtpPort: "SMTP Port",
      sender: "Sender",
      receiver: "Receiver",
      smtpPassword: "SMTP Password",
      ghLanguages: "GitHub Languages",
      ghSince: "GitHub Since",
      ghMaxRepos: "GitHub Max Repos",
      hfContentTypes: "HF Content Types",
      hfMaxPapers: "HF Max Papers",
      hfMaxModels: "HF Max Models",
      xRapidApiKey: "X RapidAPI Key",
      xRapidApiHost: "X RapidAPI Host",
      arxivCategories: "arXiv Categories",
      arxivMaxEntries: "arXiv Max Entries",
      arxivMaxPapers: "arXiv Max Papers",
      description: "默认兴趣描述",
      researcherProfile: "研究者画像",
      xAccounts: "X 账号池",
      userName: "名称",
      userReceiver: "收件邮箱",
      userFocus: "研究方向关键词",
      avatar: "头像",
      profile: "用户画像",
      appSettings: "应用设置",
      subscriptionSettings: "订阅服务设置",
      senderSettings: "发件邮箱设置",
      mailHostingSettings: "邮件托管设置",
      managedMailHint: "留空时会尝试使用 iDeer 托管发信，但稳定性和隐私都不如自托管邮箱。",
      managedMailTooltip: "如果不填写发件邮箱设置，会尝试使用运营邮箱代发，但这并不稳定。涉及隐私和稳定性时，建议托管自己的邮箱服务。",
      connectionHint: "使用当前 Base URL、API Key 和可选的 Model 做一次 OpenAI 兼容接口探测。会优先请求 /models，必要时回退到一次最小 chat/completions。",
      desktopPythonPath: "Python 解释器路径",
      desktopPythonHint: "仅桌面调试使用。填写后，启动本地服务会优先使用这个解释器，例如你的 conda 环境里的 python.exe。",
      testConnection: "测试连通性",
      testingConnection: "测试中...",
      smtpConnectionHint: "测试当前 SMTP 服务器地址和端口是否可建立网络连接。",
      testSmtp: "测试 SMTP",
      testingSmtp: "测试 SMTP 中...",
      saveProfile: "保存用户信息",
      profileSaved: "用户信息已保存",
    },
    info: {
      title: "关于 iDeer",
      slogan: "把每日值得关注的信息整理成一份清晰简报。",
      disclaimer: "请仅将 iDeer 用于合法、合规的信息追踪与研究。部分第三方接口可能触达你所在地区受限制的内容，用户需自行遵守当地法律、平台政策与研究伦理。",
      authors: "主要贡献者",
      website: "个人网站",
      githubId: "GitHub ID",
      github: "打开 GitHub 仓库",
      version: "桌面原型",
      stack: "Tauri + React + Python",
      close: "关闭",
      online: "服务在线",
      offline: "服务离线",
    },
    controls: {
      user: "用户",
      info: "Info",
      theme: "主题",
      language: "语言",
    },
    user: {
      fallbackName: "你的名字",
      fallbackFocus: "设置你的研究方向",
      openProfile: "打开用户画像",
    },
    sourceDescriptions: {
      github: "Trending 仓库和工程动态",
      huggingface: "论文与模型动态",
      twitter: "账号时间线和圈层信号",
      arxiv: "新论文抓取与筛选",
    },
    currentModelMissing: "未配置",
  },
  en: {
    appTitle: "iDeer",
    desktopTitle: "iDeer Desktop",
    brandSubtitle: "Daily intelligence briefings",
    previewBadge: "Preview",
    statusConnected: "Service connected",
    statusWaitingDesktop: "Waiting for local service",
    statusWaitingWeb: "Start the Python backend first",
    statusBackendStarted: "Local service started",
    statusBackendStopped: "Managed service stopped",
    statusConfigSaved: "Settings saved",
    statusRunDone: (date: string) => `Completed on ${date}`,
    statusRunExited: "Run exited",
    statusSocketError: "WebSocket connection error",
    sidebar: {
      home: "Overview",
      library: "Library",
    },
    home: {
      title: "Welcome back",
      description: "Run today's briefing, review past results, and manage your common settings here.",
      openSettings: "Open user hub",
      runBlockedBackend: "Start the local service before running.",
      runBlockedSources: "Choose at least one source to continue.",
      runBlockedRunning: "A run is already in progress. Please wait.",
      backend: "Backend service",
      online: "Online",
      offline: "Offline",
      startBackend: "Start local service",
      startingBackend: "Starting...",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      stopBackend: "Stop managed service",
      model: "Model",
      mail: "Email delivery",
      mailReady: "Configured",
      mailPending: "Not configured",
      noReceiver: "No default receiver yet",
      sources: "Sources",
      noSourcesActive: "No source enabled yet.",
      recentRuns: "Recent runs",
      noHistory: "No history yet. Run something to get started.",
    },
    workbench: {
      title: "Run panel",
      run: "Run now",
      running: "Running...",
      receiver: "Receiver email",
      deliveryMode: "Delivery mode",
      sourceEmails: "Source-wise",
      combinedReport: "Combined",
      both: "Send both",
      report: "Generate cross-source report",
      ideas: "Generate research ideas",
      save: "Save run history",
      description: "Interest description",
      positiveTags: "Positive",
      negativeTags: "Negative",
      positivePlaceholder: "Add preferred topics and press Enter",
      negativePlaceholder: "Add filtered topics and press Enter",
      addTag: "Add",
      saveInterest: "Save as default",
      savingInterest: "Saving...",
      scholarUrl: "Scholar URL",
      extraX: "Extra X accounts",
      researcherProfile: "Research profile",
      advanced: "Advanced settings",
      logs: "Live logs",
      outputs: "Output files",
      outputEmpty: "Generated files will appear here after the run finishes.",
      logEmpty: "Live output will appear here once the run starts.",
      refreshHistory: "Refresh history",
    },
    library: {
      title: "Run history",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      empty: "No history yet.",
      details: "Result details",
      emptyDetails: "Choose a run on the left to inspect Markdown, HTML and JSON outputs.",
      noMarkdown: "No Markdown files",
      noHtml: "No HTML files",
      noJson: "No JSON files",
    },
    settings: {
      controlCenter: "Control center",
      userCenter: "User hub",
      basic: "Basic settings",
      save: "Save settings",
      saving: "Saving...",
      preferences: "Preferences",
      language: "Language",
      theme: "Theme",
      followSystem: "Follow system",
      chinese: "中文",
      english: "English",
      dark: "Dark",
      light: "Light",
      model: "Model & delivery",
      content: "Content preferences",
      advanced: "Advanced settings",
      provider: "Provider",
      modelName: "Model",
      temperature: "Temperature",
      baseUrl: "Base URL",
      apiKey: "API Key",
      smtpServer: "SMTP Server",
      smtpPort: "SMTP Port",
      sender: "Sender",
      receiver: "Receiver",
      smtpPassword: "SMTP Password",
      ghLanguages: "GitHub Languages",
      ghSince: "GitHub Since",
      ghMaxRepos: "GitHub Max Repos",
      hfContentTypes: "HF Content Types",
      hfMaxPapers: "HF Max Papers",
      hfMaxModels: "HF Max Models",
      xRapidApiKey: "X RapidAPI Key",
      xRapidApiHost: "X RapidAPI Host",
      arxivCategories: "arXiv Categories",
      arxivMaxEntries: "arXiv Max Entries",
      arxivMaxPapers: "arXiv Max Papers",
      description: "Default interest description",
      researcherProfile: "Research profile",
      xAccounts: "X account pool",
      userName: "Name",
      userReceiver: "Receiver email",
      userFocus: "Research keywords",
      avatar: "Avatar",
      profile: "User profile",
      appSettings: "App settings",
      subscriptionSettings: "Subscription services",
      senderSettings: "Sender email settings",
      mailHostingSettings: "Mail hosting",
      managedMailHint: "If left empty, iDeer will try to send using a managed mailbox, but privacy and stability are weaker than self-hosting.",
      managedMailTooltip: "If you leave sender mail settings empty, iDeer may try a managed sender mailbox. This is less stable, and for privacy-sensitive use it is better to host your own mailbox service.",
      connectionHint: "Probe the current Base URL, API Key, and optional Model with an OpenAI-compatible request. It tries /models first, then falls back to a minimal chat/completions request when needed.",
      desktopPythonPath: "Python interpreter path",
      desktopPythonHint: "Desktop debug only. If set, iDeer will prefer this interpreter when starting the local service, for example the python.exe inside your conda environment.",
      testConnection: "Test connection",
      testingConnection: "Testing...",
      smtpConnectionHint: "Check whether the current SMTP host and port can be reached over the network.",
      testSmtp: "Test SMTP",
      testingSmtp: "Testing SMTP...",
      saveProfile: "Save profile",
      profileSaved: "Profile saved",
    },
    info: {
      title: "About iDeer",
      slogan: "Turn what matters each day into a clean, readable briefing.",
      disclaimer: "Use iDeer only for lawful, policy-compliant tracking and research. Some third-party feeds may surface content restricted in your region, and users are responsible for following local laws, platform policies, and research ethics.",
      authors: "Main Contributors",
      website: "Website",
      githubId: "GitHub ID",
      github: "Open GitHub repository",
      version: "Desktop prototype",
      stack: "Tauri + React + Python",
      close: "Close",
      online: "Service online",
      offline: "Service offline",
    },
    controls: {
      user: "User",
      info: "Info",
      theme: "Theme",
      language: "Language",
    },
    user: {
      fallbackName: "Your name",
      fallbackFocus: "Set your research focus",
      openProfile: "Open profile",
    },
    sourceDescriptions: {
      github: "Trending repositories and engineering momentum",
      huggingface: "Papers and model ecosystem updates",
      twitter: "Timeline signals and monitored accounts",
      arxiv: "Fresh papers and filtered research picks",
    },
    currentModelMissing: "Not configured",
  },
} as const;

export type AppCopy = typeof COPY.zh | typeof COPY.en;
